### ISSUE TITLE
[CLOUD] Fix KeyError: 'accountId' in cloud when customer already exists

### ISSUE THREAD

**Issue by iokiwi** [iokiwi/jsd-bulk-customer-upload#9]
```
2020-02-29 22:28:54,346 - ERROR - bulk_customer_import.bulk_customer_import - Failed to process row: ['Super Company', 'John Smith', 'john.smith@example.com']
Traceback (most recent call last):
  File "/Users/simon/Development/jsd-bulk-customer-upload/bulk_customer_import/bulk_customer_import.py", line 108, in main
    client.organization.add_customer(organization, customer)
  File "/Users/simon/Development/jsd-bulk-customer-upload/bulk_customer_import/organization.py", line 28, in add_customer
    data = {fields[0]: [customer[fields[1]]]}
KeyError: 'accountId'
```

In jira service desk cloud you need to use the customer account ID when adding a customer to the organization.

If the customer doesn't exist in jira yet then there is no issue because the account ID is returned in the data from creating a new customer via the API and can subsequently be referenced in order to add the customer to an organisation.

However if the customer already exists in jira, then the account creation step will fail due to trying to create a duplicate user and then we dont have the accountId.

We need to go and get the account ID for an existing customer.

This shouldn't be too hard in cloud but this completely breaks compatability with server and the script will need to be rearchiteched to support the processes required for these two diverging platforms respectively.

**Comment by iokiwi** [comment]
Really, Server and Cloud have just diverged to much to have a single 'script' clients that work for both - it would be possible but messy and confusing.

Instead, we need to create a common user interface to two seperate processes for server and cloud respectively.

**Comment by iokiwi** [comment]
Pretty much fixed
